# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
  vmImage: windows-latest

stages:
  - stage: terraform_validate
    displayName: terraform validate and innit
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@2
          inputs:
            terraformVersion: 'latest'
