trigger: none
pr: none

pool:
  vmImage: windows-latest

stages:
- stage: stage_cheat
  displayName: CHEAT
  jobs:
  - job:
    continueOnError: false
    steps:
    - task: CmdLine@2
      displayName: CHEAT
      inputs:
        script: |      
          echo Hello world

- stage: stage_code
  displayName: CODE
  jobs:
  - job:
    continueOnError: false
    steps:
    - task: CmdLine@2
      displayName: CODE
      inputs:
        script: |      
          echo CODE

- stage: stage_tuesdays
  displayName: TUESDAYS
  jobs:
  - job:
    continueOnError: false
    steps:
    - task: CmdLine@2
      displayName: TUESDAYS
      inputs:
        script: |      
          echo TUESDAYS