trigger: none
pr: none

pool:
  vmImage: windows-latest

stages:
- stage: download_terraform
  displayName: download Terraform from Hasicorp website
  jobs:
  - job:
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: 'latest'
    - task: TerraformCLI@0
      inputs:
        command: 'version'
        allowTelemetryCollection: false
    - task: TerraformCLI@0
      inputs:
        command: 'init'
        backendType: 'azurerm'
        backendServiceArm: 'manual-sp'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'rg-cats-eastus-1'
        backendAzureRmResourceGroupLocation: 'eastus2'
        backendAzureRmStorageAccountName: 'catstorageacc1'
        backendAzureRmStorageAccountSku: 'Standard_LRS'
        backendAzureRmContainerName: 'tfstates'
        backendAzureRmKey: 'dev-tfstate'
        allowTelemetryCollection: true
        commandOptions: '-var-file="dev/main.tfvars"'
    - task: TerraformCLI@0
      inputs:
        command: 'plan'
        environmentServiceName: 'manual-sp'
        allowTelemetryCollection: false
        commandOptions: '-var-file="dev/main.tfvars"'
