trigger: none
pr: none

pool:
  vmImage: windows-latest

variables:
  ARM_SUBSCRIPTION_ID: '3ed8bd5f-d033-4d8c-9264-88905230a957'

stages:
  - stage: terraform_validate
    displayName: terraform validate and init
    jobs:
      - job:
        continueOnError: false 
        steps:
        - task: TerraformInstaller@2
          displayName: Install Terraform
          inputs:
            terraformVersion: 'latest'
        - task: TerraformCLI@2
          displayName: Terraform init
          inputs:
              command: 'init'
              commandOptions: '-var-file="dev/main.tfvars"'
              backendType: 'azurerm'
              backendServiceArm: 'Pay-As-You-Go(3ed8bd5f-d033-4d8c-9264-88905230a957)'
              providerAzureRmSubscriptionId: $(ARM_SUBSCRIPTION_ID)
              ensureBackend: true
              backendAzureRmResourceGroupName: 'max-dev-eastus-rg-1'
              backendAzureRmResourceGroupLocation: 'eastus'
              backendAzureRmStorageAccountName: 'maxstorageaccdemo0'
              backendAzureRmStorageAccountSku: 'Standard_LRS'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'dev-tfstate'
              allowTelemetryCollection: false
          env:
            ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        - task: TerraformCLI@2
          inputs:
            command: 'validate'
            allowTelemetryCollection: false
  
  - stage: terraform_plan
    dependsOn: terraform_validate
    condition: succeeded('terraform_validate')
    displayName: Terraform Plan
    jobs:
      - job:
        steps:
        - task: TerraformInstaller@2
          displayName: Install Terraform
          inputs:
            terraformVersion: 'latest'
        - task: TerraformCLI@2
          displayName: Terraform init
          inputs:
            command: 'init'
            commandOptions: '-var-file="dev/main.tfvars"' 
            backendType: 'azurerm'
            backendServiceArm: 'Pay-As-You-Go(3ed8bd5f-d033-4d8c-9264-88905230a957)'
            providerAzureRmSubscriptionId: $(ARM_SUBSCRIPTION_ID)
            ensureBackend: true
            backendAzureRmResourceGroupName: 'max-dev-eastus-rg-1'
            backendAzureRmResourceGroupLocation: 'eastus'
            backendAzureRmStorageAccountName: 'maxstorageaccdemo0'
            backendAzureRmStorageAccountSku: 'Standard_LRS'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'dev-tfstate'
            allowTelemetryCollection: false
          env:
            ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
                 
        - task: TerraformCLI@2
          displayName: Terraform plan
          inputs:
            command: 'plan'
            allowTelemetryCollection: false
            commandOptions: '-var-file="dev/main.tfvars"'
            
  - stage: terraform_apply
    condition: succeeded('terraform_plan')
    dependsOn: terraform_plan
    displayName: Terraform Apply
    jobs:
    - job:
      steps:     
      
      - task: TerraformInstaller@2
        displayName: Install Terraform
        inputs:
          terraformVersion: 'latest'
      - task: TerraformCLI@2
        displayName: Terraform init
        inputs:
          command: 'init'
          commandOptions: '-var-file="dev/main.tfvars"'   
          backendType: 'azurerm'
          backendServiceArm: 'Pay-As-You-Go(3ed8bd5f-d033-4d8c-9264-88905230a957)'
          providerAzureRmSubscriptionId: $(ARM_SUBSCRIPTION_ID)
          ensureBackend: true
          backendAzureRmResourceGroupName: 'max-dev-eastus-rg-1'
          backendAzureRmResourceGroupLocation: 'eastus'
          backendAzureRmStorageAccountName: 'maxstorageaccdemo0'
          backendAzureRmStorageAccountSku: 'Standard_LRS'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'dev-tfstate'
          allowTelemetryCollection: false
        env:
          ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
          
      - task: TerraformCLI@2
        displayName: Terraform apply
        inputs:
          command: 'apply'
          commandOptions: '-var-file="dev/main.tfvars"'
          allowTelemetryCollection: false
