trigger: none
pr: none

pool:
  vmImage: windows-latest

stages:
- stage: download_terraform
  displayName: download Terraform from Hasicorp website
  jobs:
  - job:
    steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'
    - task: TerraformCLI@0
      displayName: Terraform version
      inputs:
        command: 'version'
        allowTelemetryCollection: false
    - task: TerraformCLI@0
      displayName: Terraform init
      inputs:
        command: 'init'
        backendType: 'azurerm'
        backendServiceArm: 'terraform-sp-63498'
        ensureBackend: true
        backendAzureRmResourceGroupName: 'rex-dev-eastus-rg-1'
        backendAzureRmResourceGroupLocation: 'eastus'
        backendAzureRmStorageAccountName: 'rextorageacc001'
        backendAzureRmStorageAccountSku: 'Standard_LRS'
        backendAzureRmContainerName: 'tfstates'
        backendAzureRmKey: 'dev-tfstate'
        allowTelemetryCollection: false
        commandOptions: '-var-file="dev/main.tfvars"'
    - task: TerraformCLI@0
      displayName: Terraform plan
      inputs:
        command: 'plan'
        environmentServiceName: 'terraform-sp-63498'
        allowTelemetryCollection: false
        commandOptions: '-var-file="dev/main.tfvars"'
    - task: TerraformCLI@0
      displayName: Terraform apply
      inputs:
        command: 'apply'
        environmentServiceName: 'terraform-sp-63498'
        commandOptions: '-var-file="dev/main.tfvars"'
        allowTelemetryCollection: false
